### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###
GET localhost:8080

###
GET localhost:8080/todo

###
POST localhost:8080/todo

{
"item": "thank you Jesus!"
}

###

GET localhost:8080/search?q=thank


###
DELETE localhost:8080/todo

{
"item": "do golang in 5 days"
}
